# Generated by Django 4.2.2 on 2023-06-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                default="/home/sumit/Desktop/Django Projects/S_M_S/student_management_system/static/assets/img/profiles/default_avatar.jpg",
                upload_to="media/profile_pic",
            ),
        ),
    ]
