# Generated by Django 4.2.2 on 2023-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_management_app",
            "0005_attendance_created_at_attendance_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationstudent",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
