# Generated by Django 4.2.2 on 2023-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0007_feedbackstudent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackstaffs",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
