# Generated by Django 4.2.2 on 2023-06-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Student_app", "0001_initial"),
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="student_management_app.courses",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="session_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.sessionyearmodel",
            ),
        ),
    ]
