# Generated by Django 4.2.2 on 2023-06-22 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Student_app", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="course",
            new_name="course_id",
        ),
    ]
