# Generated by Django 4.2.2 on 2023-06-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Student_app", "0003_rename_course_students_course_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="session_year",
            new_name="session_year_id",
        ),
    ]
